# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

modVersion=1.11.1
mavenGroup=io.github.ultrusbot
archivesBaseName=moborigins
modDisplayName=Mob Origins

githubRepoName=MobOrigins
githubTargetBranch=1.21

minecraftVersions=1.21.1
modLoaders=Fabric,Quilt
releaseFileType=release


modrinthProjectId=moborigins
#modrinthEmbeddedProjects=
modrinthRequiredProjects=origins
#modrinthOptionalProjects=

curseforgeProjectId=449974
#curseforgeEmbeddedProjects=midnightlib
curseforgeRequiredProjects=origins
#curseforgeOptionalProjects=



# This makes it so the modrinth, curseforge, and github release doesn't actually publish the mod, and only does a test run.
testRelease=false

syncBody=true

mixin.debug.export=true
mixin.debug.verbose=true
mixin.debug.strict=true

fabric.development=true
fabric.dli.env=local
fabric.dli.username=DevUser