pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
        maven { url = 'https://maven.quiltmc.org/repository/release' }
        maven { url = 'https://server.bbkr.space/artifactory/libs-release/' }
    }

    plugins {
        id("fabric-loom") version "1.6-SNAPSHOT"
    }
}

dependencyResolutionManagement {
    versionCatalogs {
        create("extraLibs") {
            from(files("gradle/libs.versions.toml"))
        }
    }
}
